# Generated by Django 3.1.7 on 2021-03-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='ceated_by',
            new_name='created_by',
        ),
    ]
